import { defineMigration } from '@holo-js/db'

export default defineMigration({
  async up({ schema }) {
    await schema.createTable('categories', (table) => {
      table.string('id').primaryKey()
      table.string('tenantId')
      table.string('name')
      table.string('slug')
      table.timestamp('createdAt').defaultNow()
      table.timestamp('updatedAt').defaultNow()
      table.unique(['tenantId', 'slug'], 'categories_tenant_slug_unique')
    })
    await schema.createTable('tags', (table) => {
      table.string('id').primaryKey()
      table.string('tenantId')
      table.string('name')
      table.string('slug')
      table.timestamp('createdAt').defaultNow()
      table.timestamp('updatedAt').defaultNow()
      table.unique(['tenantId', 'slug'], 'tags_tenant_slug_unique')
    })
    await schema.createTable('users', (table) => {
      table.string('id').primaryKey()
      table.string('name')
      table.string('email').unique()
      table.string('password')
      table.string('role')
      table.string('tenantId')
      table.timestamp('createdAt').defaultNow()
      table.timestamp('updatedAt').defaultNow()
    })
    await schema.createTable('memberships', (table) => {
      table.string('id').primaryKey()
      table.string('tenantId')
      table.string('userId')
      table.string('roleKey')
      table.foreign('userId').references('id').on('users').cascadeOnDelete()
      table.unique(['tenantId', 'userId'], 'memberships_tenant_user_unique')
    })
    await schema.createTable('posts', (table) => {
      table.string('id').primaryKey()
      table.string('tenantId')
      table.string('title')
      table.string('slug')
      table.text('excerpt')
      table.text('body')
      table.string('status')
      table.string('categoryId')
      table.string('authorId')
      table.string('featuredMediaId').nullable()
      table.timestamp('publishedAt').nullable()
      table.string('category')
      table.string('city')
      table.timestamp('createdAt').defaultNow()
      table.timestamp('updatedAt').defaultNow()
      table.foreign('categoryId').references('id').on('categories')
      table.foreign('authorId').references('id').on('users')
      table.unique(['tenantId', 'slug'], 'posts_tenant_slug_unique')
    })
    await schema.createTable('comments', (table) => {
      table.string('id').primaryKey()
      table.string('tenantId')
      table.string('postId').nullable()
      table.string('authorName')
      table.text('body')
      table.string('status')
      table.timestamp('createdAt').defaultNow()
      table.timestamp('updatedAt').defaultNow()
      table.foreign('postId').references('id').on('posts').cascadeOnDelete()
      table.index(['tenantId', 'postId'])
    })
    await schema.createTable('media', (table) => {
      table.string('id').primaryKey()
      table.string('tenantId')
      table.string('disk')
      table.string('path')
      table.string('mime')
      table.integer('size')
      table.string('alt')
      table.timestamp('createdAt').defaultNow()
      table.timestamp('updatedAt').defaultNow()
      table.unique(['tenantId', 'path'], 'media_tenant_path_unique')
    })
    await schema.createTable('post_tags', (table) => {
      table.string('id').primaryKey()
      table.string('tenantId')
      table.string('postId')
      table.string('tagId')
      table.integer('position').default(0)
      table.foreign('postId').references('id').on('posts').cascadeOnDelete()
      table.foreign('tagId').references('id').on('tags').cascadeOnDelete()
      table.unique(['tenantId', 'postId', 'tagId'], 'post_tags_tenant_unique')
    })
  },
  async down({ schema }) {
    await schema.dropTable('post_tags')
    await schema.dropTable('media')
    await schema.dropTable('comments')
    await schema.dropTable('posts')
    await schema.dropTable('memberships')
    await schema.dropTable('users')
    await schema.dropTable('tags')
    await schema.dropTable('categories')
  },
})
