import { defineMigration } from '@holo-js/db'

export default defineMigration({
  async up({ schema }) {
    await schema.createTable('users', (table) => {
      table.string('id').primaryKey()
      table.string('name')
      table.string('email').unique()
      table.string('password')
      table.string('role')
      table.string('tenantId').nullable()
      table.timestamps()
    })
    await schema.createTable('categories', (table) => {
      table.string('id').primaryKey()
      table.string('tenantId')
      table.string('name')
      table.string('slug')
      table.timestamps()
      table.unique(['tenantId', 'slug'])
      table.index(['tenantId'])
    })
    await schema.createTable('tags', (table) => {
      table.string('id').primaryKey()
      table.string('tenantId')
      table.string('name')
      table.string('slug')
      table.timestamps()
      table.unique(['tenantId', 'slug'])
      table.index(['tenantId'])
    })
    await schema.createTable('media', (table) => {
      table.string('id').primaryKey()
      table.string('tenantId')
      table.string('disk').default('private')
      table.string('path')
      table.string('mime')
      table.integer('size')
      table.string('alt')
      table.timestamps()
      table.index(['tenantId'])
    })
    await schema.createTable('posts', (table) => {
      table.string('id').primaryKey()
      table.string('tenantId')
      table.string('title')
      table.string('slug')
      table.text('excerpt')
      table.text('body')
      table.string('status')
      table.string('categoryId')
      table.string('authorId')
      table.string('featuredMediaId').nullable()
      table.string('category')
      table.string('city')
      table.timestamps()
      table.unique(['tenantId', 'slug'])
      table.index(['tenantId', 'status'])
      table.index(['tenantId', 'categoryId'])
    })
    await schema.createTable('comments', (table) => {
      table.string('id').primaryKey()
      table.string('tenantId')
      table.string('postId')
      table.string('authorName')
      table.text('body')
      table.string('status').default('pending')
      table.timestamps()
      table.index(['tenantId', 'postId'])
      table.index(['tenantId', 'status'])
    })
    await schema.createTable('memberships', (table) => {
      table.string('id').primaryKey()
      table.string('tenantId')
      table.string('userId')
      table.string('roleKey')
      table.timestamps()
      table.unique(['tenantId', 'userId'])
      table.index(['tenantId', 'roleKey'])
    })
    await schema.createTable('post_tags', (table) => {
      table.string('id').primaryKey()
      table.string('tenantId')
      table.string('postId')
      table.string('tagId')
      table.timestamps()
      table.unique(['tenantId', 'postId', 'tagId'])
      table.index(['tenantId', 'postId'])
    })
  },
  async down({ schema }) {
    await schema.dropTable('post_tags')
    await schema.dropTable('memberships')
    await schema.dropTable('comments')
    await schema.dropTable('posts')
    await schema.dropTable('media')
    await schema.dropTable('tags')
    await schema.dropTable('categories')
    await schema.dropTable('users')
  },
})
