export {
  isClusterDefinition,
  isDiscoverableBuilder,
  isDiscoverableDefinition,
  isDiscoverableKind,
  isExportDefinition,
  isImportDefinition,
  isPageDefinition,
  isPanelDefinition,
  isPluginDefinition,
  isRelationManagerDefinition,
  isResourceDefinition,
  isWidgetDefinition,
  markDiscoverableDefinition,
} from '@holo-js/panels-core'
